//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.orienteering.datastandard._3;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.orienteering.datastandard._3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.orienteering.datastandard._3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TeamMemberRaceResult }
     * 
     * @return
     *     the new instance of {@link TeamMemberRaceResult }
     */
    public TeamMemberRaceResult createTeamMemberRaceResult() {
        return new TeamMemberRaceResult();
    }

    /**
     * Create an instance of {@link CompetitorList }
     * 
     * @return
     *     the new instance of {@link CompetitorList }
     */
    public CompetitorList createCompetitorList() {
        return new CompetitorList();
    }

    /**
     * Create an instance of {@link Competitor }
     * 
     * @return
     *     the new instance of {@link Competitor }
     */
    public Competitor createCompetitor() {
        return new Competitor();
    }

    /**
     * Create an instance of {@link Extensions }
     * 
     * @return
     *     the new instance of {@link Extensions }
     */
    public Extensions createExtensions() {
        return new Extensions();
    }

    /**
     * Create an instance of {@link OrganisationList }
     * 
     * @return
     *     the new instance of {@link OrganisationList }
     */
    public OrganisationList createOrganisationList() {
        return new OrganisationList();
    }

    /**
     * Create an instance of {@link Organisation }
     * 
     * @return
     *     the new instance of {@link Organisation }
     */
    public Organisation createOrganisation() {
        return new Organisation();
    }

    /**
     * Create an instance of {@link EventList }
     * 
     * @return
     *     the new instance of {@link EventList }
     */
    public EventList createEventList() {
        return new EventList();
    }

    /**
     * Create an instance of {@link Event }
     * 
     * @return
     *     the new instance of {@link Event }
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link ClassList }
     * 
     * @return
     *     the new instance of {@link ClassList }
     */
    public ClassList createClassList() {
        return new ClassList();
    }

    /**
     * Create an instance of {@link Class }
     * 
     * @return
     *     the new instance of {@link Class }
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link EntryList }
     * 
     * @return
     *     the new instance of {@link EntryList }
     */
    public EntryList createEntryList() {
        return new EntryList();
    }

    /**
     * Create an instance of {@link TeamEntry }
     * 
     * @return
     *     the new instance of {@link TeamEntry }
     */
    public TeamEntry createTeamEntry() {
        return new TeamEntry();
    }

    /**
     * Create an instance of {@link PersonEntry }
     * 
     * @return
     *     the new instance of {@link PersonEntry }
     */
    public PersonEntry createPersonEntry() {
        return new PersonEntry();
    }

    /**
     * Create an instance of {@link CourseData }
     * 
     * @return
     *     the new instance of {@link CourseData }
     */
    public CourseData createCourseData() {
        return new CourseData();
    }

    /**
     * Create an instance of {@link RaceCourseData }
     * 
     * @return
     *     the new instance of {@link RaceCourseData }
     */
    public RaceCourseData createRaceCourseData() {
        return new RaceCourseData();
    }

    /**
     * Create an instance of {@link StartList }
     * 
     * @return
     *     the new instance of {@link StartList }
     */
    public StartList createStartList() {
        return new StartList();
    }

    /**
     * Create an instance of {@link ClassStart }
     * 
     * @return
     *     the new instance of {@link ClassStart }
     */
    public ClassStart createClassStart() {
        return new ClassStart();
    }

    /**
     * Create an instance of {@link Iof3ResultList }
     * 
     * @return
     *     the new instance of {@link Iof3ResultList }
     */
    public Iof3ResultList createResultList() {
        return new Iof3ResultList();
    }

    /**
     * Create an instance of {@link Iof3ClassResult }
     * 
     * @return
     *     the new instance of {@link Iof3ClassResult }
     */
    public Iof3ClassResult createClassResult() {
        return new Iof3ClassResult();
    }

    /**
     * Create an instance of {@link ServiceRequestList }
     * 
     * @return
     *     the new instance of {@link ServiceRequestList }
     */
    public ServiceRequestList createServiceRequestList() {
        return new ServiceRequestList();
    }

    /**
     * Create an instance of {@link OrganisationServiceRequest }
     * 
     * @return
     *     the new instance of {@link OrganisationServiceRequest }
     */
    public OrganisationServiceRequest createOrganisationServiceRequest() {
        return new OrganisationServiceRequest();
    }

    /**
     * Create an instance of {@link PersonServiceRequest }
     * 
     * @return
     *     the new instance of {@link PersonServiceRequest }
     */
    public PersonServiceRequest createPersonServiceRequest() {
        return new PersonServiceRequest();
    }

    /**
     * Create an instance of {@link ControlCardList }
     * 
     * @return
     *     the new instance of {@link ControlCardList }
     */
    public ControlCardList createControlCardList() {
        return new ControlCardList();
    }

    /**
     * Create an instance of {@link ControlCard }
     * 
     * @return
     *     the new instance of {@link ControlCard }
     */
    public ControlCard createControlCard() {
        return new ControlCard();
    }

    /**
     * Create an instance of {@link Id }
     * 
     * @return
     *     the new instance of {@link Id }
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link Person }
     * 
     * @return
     *     the new instance of {@link Person }
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     * @return
     *     the new instance of {@link PersonName }
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link Score }
     * 
     * @return
     *     the new instance of {@link Score }
     */
    public Score createScore() {
        return new Score();
    }

    /**
     * Create an instance of {@link Role }
     * 
     * @return
     *     the new instance of {@link Role }
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link EntryReceiver }
     * 
     * @return
     *     the new instance of {@link EntryReceiver }
     */
    public EntryReceiver createEntryReceiver() {
        return new EntryReceiver();
    }

    /**
     * Create an instance of {@link Race }
     * 
     * @return
     *     the new instance of {@link Race }
     */
    public Race createRace() {
        return new Race();
    }

    /**
     * Create an instance of {@link EventURL }
     * 
     * @return
     *     the new instance of {@link EventURL }
     */
    public EventURL createEventURL() {
        return new EventURL();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     * @return
     *     the new instance of {@link Schedule }
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link InformationItem }
     * 
     * @return
     *     the new instance of {@link InformationItem }
     */
    public InformationItem createInformationItem() {
        return new InformationItem();
    }

    /**
     * Create an instance of {@link ClassType }
     * 
     * @return
     *     the new instance of {@link ClassType }
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link RaceClass }
     * 
     * @return
     *     the new instance of {@link RaceClass }
     */
    public RaceClass createRaceClass() {
        return new RaceClass();
    }

    /**
     * Create an instance of {@link Fee }
     * 
     * @return
     *     the new instance of {@link Fee }
     */
    public Fee createFee() {
        return new Fee();
    }

    /**
     * Create an instance of {@link AssignedFee }
     * 
     * @return
     *     the new instance of {@link AssignedFee }
     */
    public AssignedFee createAssignedFee() {
        return new AssignedFee();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     * @return
     *     the new instance of {@link Amount }
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link TeamEntryPerson }
     * 
     * @return
     *     the new instance of {@link TeamEntryPerson }
     */
    public TeamEntryPerson createTeamEntryPerson() {
        return new TeamEntryPerson();
    }

    /**
     * Create an instance of {@link StartTimeAllocationRequest }
     * 
     * @return
     *     the new instance of {@link StartTimeAllocationRequest }
     */
    public StartTimeAllocationRequest createStartTimeAllocationRequest() {
        return new StartTimeAllocationRequest();
    }

    /**
     * Create an instance of {@link StartName }
     * 
     * @return
     *     the new instance of {@link StartName }
     */
    public StartName createStartName() {
        return new StartName();
    }

    /**
     * Create an instance of {@link PersonStart }
     * 
     * @return
     *     the new instance of {@link PersonStart }
     */
    public PersonStart createPersonStart() {
        return new PersonStart();
    }

    /**
     * Create an instance of {@link PersonRaceStart }
     * 
     * @return
     *     the new instance of {@link PersonRaceStart }
     */
    public PersonRaceStart createPersonRaceStart() {
        return new PersonRaceStart();
    }

    /**
     * Create an instance of {@link TeamStart }
     * 
     * @return
     *     the new instance of {@link TeamStart }
     */
    public TeamStart createTeamStart() {
        return new TeamStart();
    }

    /**
     * Create an instance of {@link TeamMemberStart }
     * 
     * @return
     *     the new instance of {@link TeamMemberStart }
     */
    public TeamMemberStart createTeamMemberStart() {
        return new TeamMemberStart();
    }

    /**
     * Create an instance of {@link TeamMemberRaceStart }
     * 
     * @return
     *     the new instance of {@link TeamMemberRaceStart }
     */
    public TeamMemberRaceStart createTeamMemberRaceStart() {
        return new TeamMemberRaceStart();
    }

    /**
     * Create an instance of {@link Iof3PersonResult }
     * 
     * @return
     *     the new instance of {@link Iof3PersonResult }
     */
    public Iof3PersonResult createPersonResult() {
        return new Iof3PersonResult();
    }

    /**
     * Create an instance of {@link PersonRaceResult }
     * 
     * @return
     *     the new instance of {@link PersonRaceResult }
     */
    public PersonRaceResult createPersonRaceResult() {
        return new PersonRaceResult();
    }

    /**
     * Create an instance of {@link TeamResult }
     * 
     * @return
     *     the new instance of {@link TeamResult }
     */
    public TeamResult createTeamResult() {
        return new TeamResult();
    }

    /**
     * Create an instance of {@link TeamMemberResult }
     * 
     * @return
     *     the new instance of {@link TeamMemberResult }
     */
    public TeamMemberResult createTeamMemberResult() {
        return new TeamMemberResult();
    }

    /**
     * Create an instance of {@link OverallResult }
     * 
     * @return
     *     the new instance of {@link OverallResult }
     */
    public OverallResult createOverallResult() {
        return new OverallResult();
    }

    /**
     * Create an instance of {@link ControlAnswer }
     * 
     * @return
     *     the new instance of {@link ControlAnswer }
     */
    public ControlAnswer createControlAnswer() {
        return new ControlAnswer();
    }

    /**
     * Create an instance of {@link Iof3SplitTime }
     * 
     * @return
     *     the new instance of {@link Iof3SplitTime }
     */
    public Iof3SplitTime createSplitTime() {
        return new Iof3SplitTime();
    }

    /**
     * Create an instance of {@link Route }
     * 
     * @return
     *     the new instance of {@link Route }
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link Leg }
     * 
     * @return
     *     the new instance of {@link Leg }
     */
    public Leg createLeg() {
        return new Leg();
    }

    /**
     * Create an instance of {@link Control }
     * 
     * @return
     *     the new instance of {@link Control }
     */
    public Control createControl() {
        return new Control();
    }

    /**
     * Create an instance of {@link GeoPosition }
     * 
     * @return
     *     the new instance of {@link GeoPosition }
     */
    public GeoPosition createGeoPosition() {
        return new GeoPosition();
    }

    /**
     * Create an instance of {@link Map }
     * 
     * @return
     *     the new instance of {@link Map }
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link Image }
     * 
     * @return
     *     the new instance of {@link Image }
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link MapPosition }
     * 
     * @return
     *     the new instance of {@link MapPosition }
     */
    public MapPosition createMapPosition() {
        return new MapPosition();
    }

    /**
     * Create an instance of {@link ClassCourseAssignment }
     * 
     * @return
     *     the new instance of {@link ClassCourseAssignment }
     */
    public ClassCourseAssignment createClassCourseAssignment() {
        return new ClassCourseAssignment();
    }

    /**
     * Create an instance of {@link PersonCourseAssignment }
     * 
     * @return
     *     the new instance of {@link PersonCourseAssignment }
     */
    public PersonCourseAssignment createPersonCourseAssignment() {
        return new PersonCourseAssignment();
    }

    /**
     * Create an instance of {@link TeamCourseAssignment }
     * 
     * @return
     *     the new instance of {@link TeamCourseAssignment }
     */
    public TeamCourseAssignment createTeamCourseAssignment() {
        return new TeamCourseAssignment();
    }

    /**
     * Create an instance of {@link TeamMemberCourseAssignment }
     * 
     * @return
     *     the new instance of {@link TeamMemberCourseAssignment }
     */
    public TeamMemberCourseAssignment createTeamMemberCourseAssignment() {
        return new TeamMemberCourseAssignment();
    }

    /**
     * Create an instance of {@link Course }
     * 
     * @return
     *     the new instance of {@link Course }
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link SimpleCourse }
     * 
     * @return
     *     the new instance of {@link SimpleCourse }
     */
    public SimpleCourse createSimpleCourse() {
        return new SimpleCourse();
    }

    /**
     * Create an instance of {@link SimpleRaceCourse }
     * 
     * @return
     *     the new instance of {@link SimpleRaceCourse }
     */
    public SimpleRaceCourse createSimpleRaceCourse() {
        return new SimpleRaceCourse();
    }

    /**
     * Create an instance of {@link CourseControl }
     * 
     * @return
     *     the new instance of {@link CourseControl }
     */
    public CourseControl createCourseControl() {
        return new CourseControl();
    }

    /**
     * Create an instance of {@link Service }
     * 
     * @return
     *     the new instance of {@link Service }
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link ServiceRequest }
     * 
     * @return
     *     the new instance of {@link ServiceRequest }
     */
    public ServiceRequest createServiceRequest() {
        return new ServiceRequest();
    }

    /**
     * Create an instance of {@link Account }
     * 
     * @return
     *     the new instance of {@link Account }
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link Address }
     * 
     * @return
     *     the new instance of {@link Address }
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Country }
     * 
     * @return
     *     the new instance of {@link Country }
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     * @return
     *     the new instance of {@link Contact }
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link DateAndOptionalTime }
     * 
     * @return
     *     the new instance of {@link DateAndOptionalTime }
     */
    public DateAndOptionalTime createDateAndOptionalTime() {
        return new DateAndOptionalTime();
    }

    /**
     * Create an instance of {@link LanguageString }
     * 
     * @return
     *     the new instance of {@link LanguageString }
     */
    public LanguageString createLanguageString() {
        return new LanguageString();
    }

    /**
     * Create an instance of {@link TeamMemberRaceResult.TimeBehind }
     * 
     * @return
     *     the new instance of {@link TeamMemberRaceResult.TimeBehind }
     */
    public TeamMemberRaceResult.TimeBehind createTeamMemberRaceResultTimeBehind() {
        return new TeamMemberRaceResult.TimeBehind();
    }

    /**
     * Create an instance of {@link TeamMemberRaceResult.Position }
     * 
     * @return
     *     the new instance of {@link TeamMemberRaceResult.Position }
     */
    public TeamMemberRaceResult.Position createTeamMemberRaceResultPosition() {
        return new TeamMemberRaceResult.Position();
    }

}
